# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livraria.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elivraria.proto\x12\x08livraria\"6\n\x07Usuario\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x1b\n\x08Resposta\x12\x0f\n\x07message\x18\x01 \x01(\t\"O\n\x05Livro\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x0b\n\x03qtd\x18\x04 \x01(\x05\x12\r\n\x05valor\x18\x05 \x01(\x02\"\x16\n\x05Index\x12\r\n\x05index\x18\x01 \x01(\x05\"-\n\rPedidoUsuario\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\"O\n\x06Pedido\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0b\n\x03qtd\x18\x04 \x01(\x05\x12\r\n\x05total\x18\x05 \x01(\x02\x32\xde\x02\n\x08Livraria\x12\x32\n\tCadastrar\x12\x11.livraria.Usuario\x1a\x12.livraria.Resposta\x12.\n\x05Login\x12\x11.livraria.Usuario\x1a\x12.livraria.Resposta\x12\x35\n\x0e\x41\x64icionarLivro\x12\x0f.livraria.Livro\x1a\x12.livraria.Resposta\x12*\n\x06Listar\x12\x0f.livraria.Index\x1a\x0f.livraria.Livro\x12.\n\x07Iniciar\x12\x0f.livraria.Index\x1a\x12.livraria.Resposta\x12-\n\x05Pedir\x12\x10.livraria.Pedido\x1a\x12.livraria.Resposta\x12,\n\x07Pedidos\x12\x0f.livraria.Index\x1a\x10.livraria.Pedidob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livraria_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=28
  _globals['_USUARIO']._serialized_end=82
  _globals['_RESPOSTA']._serialized_start=84
  _globals['_RESPOSTA']._serialized_end=111
  _globals['_LIVRO']._serialized_start=113
  _globals['_LIVRO']._serialized_end=192
  _globals['_INDEX']._serialized_start=194
  _globals['_INDEX']._serialized_end=216
  _globals['_PEDIDOUSUARIO']._serialized_start=218
  _globals['_PEDIDOUSUARIO']._serialized_end=263
  _globals['_PEDIDO']._serialized_start=265
  _globals['_PEDIDO']._serialized_end=344
  _globals['_LIVRARIA']._serialized_start=347
  _globals['_LIVRARIA']._serialized_end=697
# @@protoc_insertion_point(module_scope)
